### ISSUE TITLE
prelauch.sh contains multiple errors

### ISSUE THREAD

**Issue by ekrekeler** [nh-mike/gravity-sync-docker#1]
First of all, prelauch.sh exits with an error code:
```
$ docker run -t -i -v "/path/to/.ssh:/root/.ssh:rw" --rm docker_gravitysync /usr/local/bin/prelaunch.sh
What is the hostname / IP of the remote host?
192.168.x.x
Is the remote SSH server on port 22?
/usr/local/bin/prelaunch.sh: line 24: syntax error near unexpected token `;'
/usr/local/bin/prelaunch.sh: line 24: `else;'
```

Removing the semicolon on line 24 solves this issue.

Next, if the user used to create the 'gravitysync' user on the remote host requires password for sudo, this will not work without a tty session on the SSH command, resulting in the error:
`sudo: no tty present and no askpass program specified`

This can be fixed by adding the `-t` flag to the SSH command.

Next problem is the readYesNo function. It doesn't ever prompt the user because of the way it is called, and just assumes yes. It should be used like this in if statements:
```
if readYesNo; then
    [...]
```

Other thing wrong with it is that the `echo True` and `echo False`  will not be picked up by the if statement. You should just return true or false:
```
    if echo "$answer" | grep -iq "^y" ;then
        true
    else
        false
    fi
```

Sending multiple commands over ssh needs to be enclosed in quotations. Otherwise bash will interpret commands after `&&` to be separate commands. Like so:
```
    ssh -t -o "StrictHostKeyChecking no" ${username}@${remote_host} ' \
        sudo adduser gravitysync && \
        sudo usermod -a -G sudo gravitysync && \
        sudo usermod -a -G docker gravitysync'
``` 

Last couple ones are more like suggestions. First, the gravitysync user should be allowed to execute sudo commands without password. Missing this will cause problems later. Add this line after adding gravitysync to groups:
`echo "gravitysync ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/gravitysync > /dev/null`

Finally, I would recommend disabling password login for the gravitysync user after making this change for security reasons. Since we copied the SSH keys, we don't need it anymore. This line can go after the SSH keys are copied.
```
if [ $remote_user == "gravitysync" ]; then
    echo "Disabling password login for gravitysync user"
    ssh ${remote_user}@${remote_host} sudo passwd -d gravitysync
fi
```

I have tested the changes and attached the updated script. Feel free to edit as needed.
[prelaunch.sh.txt](https://github.com/nh-mike/gravity-sync-docker/files/6007874/prelaunch.sh.txt)

**Comment by ekrekeler** [comment]
After successfully getting prelaunch to run, it looks like there are multiple errors in other scripts as well. I will see if I can get it working and submit a pull request sometime for this and the other scripts.

**Comment by ekrekeler** [comment]
As promised, I have opened a pull request to fix these errors and provide other enhancements.
#2

**Comment by nh-mike** [comment]
Again, thanks for your contribution. I am happy with the changes you have supplied, and have merged them back in.
