### ISSUE TITLE
Running in Kubernetes

### ISSUE THREAD

**Issue by tsrats** [nh-mike/gravity-sync-docker#6]
Hello!

I came across this repo as a possible way to run a stateless pi-hole in Kubernetes, syncing from a physical Pi on startup, but ran into one snag. This relies on `/var/run/docker.sock`, but Kubernetes is moving away from Docker and I am using Containerd, which has no equivalent. 

I was wondering what part of this container relies on `/var/run/docker.sock` as I could not easily figure it out myself. If there is a way to remove this dependency, then it will be more useful in situations like mine.

Thanks in advance for any insight!

**Comment by tsrats** [comment]
Upon further investigation inside the container, this is a gravity sync requirement. Sorry about that!

**Comment by nh-mike** [comment]
Hi @tsrats no, that's quite alright.

I myself have not used Kubernetes, and so I do not know how one could go about administrating this. If you're in no great hurry, and you are willing to work with me and my millions of questions and tests, I'm sure we could get this added into GravitySync upstream and then after more tries and testing, I could add compatibility to my image.

I'm quite willing to give it a go.

**Comment by tsrats** [comment]
Hi @nh-mike! If you would like I can work with you on this, but I have actually given up completely on the PiHole Docker container and made a seperate VM for it. 

My issue here was sharing the pihole binary in `/usr/local/bin/` between the two containers, and without making a Dockerfile that added pihole locally to the gravity-sync container, I'm not sure how they would both see it.

**Comment by nh-mike** [comment]
Glad to hear you've got a solution! I won't waste either of our time if it's not likely to help anyone though.

Cheers.

**Comment by nh-mike** [comment]
No worries, I won't waste either of our times if it's of no use to you.

Yeah in that case you'd need one pihole locally inside the same container or VM as Gravity Sync, and the other accessible over SSH.

I hope it works out well for you.

Cheers.
