### ISSUE TITLE
Support for remote host docker image

### ISSUE THREAD

**Issue by hppyworld** [nh-mike/gravity-sync-docker#7]
Hello, is it possible to also support remote host where main pihole is running. There also we can have gravity sync image so we don’t need to create user on local machine and gravity sync works directly between 2 docker containers? 
This is mainly for security and cleanliness of  host machine. So we use only docker images to do that. 
Thanks

**Comment by nh-mike** [comment]
Hi @hppyworld do you mean so communication is between 2 gravitysync demons, rather than over SSH?

**Comment by hppyworld** [comment]
Thanks for reply. 
if demons are possible thats good but if not then SSH within remote docker container. 
thanks

**Comment by nh-mike** [comment]
GravitySync does not support demons. I suppose I could set up an SSH server within the image based on an environmental variable.

Bear with me and I'll look into it.

**Comment by hppyworld** [comment]
Great. Thanks.

**Comment by nh-mike** [comment]
Hi @hppyworld 

I was thinking about this, and realised that adding an SSH server to this image would be unnecessary, as we only need GravitySync itself on one server, so it would only be acting as an SSH server on the other server.

A better solution would be to use an SSH server image, such as linuxserver/openssh-server which I use during testing;
https://github.com/nh-mike/gravity-sync-docker/blob/c84bb13bf9c6991fd4465cdeea8538e4e5895696/docker-testenvironment-compose.yml#L5
and then import the PiHole volumes and docker socket, install the docker executable within the SSH container, and set up your SSH keys.
I expect that the docker executable can be installed during startup using docker cmd, but also something would need to be done to prevent the container from shutting down immediately after... I'll play with this and get back to you.

**Comment by nh-mike** [comment]
Ok, so I've had a bit of a play around and I was able to get the dependencies installed. What I had to do, was to create my own pre-initialisation bash script, mount that into the container and execute it. Assuming you're using Docker Compose, using the following options in your compose file (naturally change them to suit your setup);
````
    entrypoint: "/preinit.sh"
    volumes:
       - "/docker/ssh/preinit.sh:/preinit.sh:ro"
````

And then this script for `/docker/ssh/preinit.sh`;
````
#!/bin/bash
apk add sqlite rsync docker
/init
````

Of course make sure to `chmod+x /docker/ssh/preinit.sh`

Other than that, make sure to mount the [pihole directories](https://github.com/nh-mike/gravity-sync-docker/blob/c84bb13bf9c6991fd4465cdeea8538e4e5895696/dev_scripts/test#L27), the [docker socket](https://github.com/nh-mike/gravity-sync-docker/blob/c84bb13bf9c6991fd4465cdeea8538e4e5895696/dev_scripts/test#L27), map the SSH port and [create your SSH keys](https://github.com/nh-mike/gravity-sync-docker/blob/c84bb13bf9c6991fd4465cdeea8538e4e5895696/dev_scripts/test#L27).

I hope this helps you. I'll close this issue now but don't be afraid to come back here if you need any more pointers.

**Comment by hppyworld** [comment]
@nh-mike Thanks for quick solution. I will try it soon. 
just quick question have you tested this solution for pihole2 and pihole3 syncing with pihole1.
 will it not crash when 2 extra pihole will try to sync at the same time with main pihole? Thanks

**Comment by nh-mike** [comment]
GravitySync is designed to sync only 2 PiHoles. Anything over and on top of that is officially unsupported.

That said, this question was raised on the GravitySync Issues tracker almost a year ago. Have a look at my response there;
https://github.com/vmstan/gravity-sync/discussions/145#discussioncomment-343579

I have never tested this myself, but theoretically I think it could work (however I don't guarantee it will be a smooth experience).
